### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by azataiot** [azataiot/python-project-template#14]
- [ ] We don't need `.VERSION` anymore. 
- [ ] Should have a command to init the new project (not from the readme and `pyproject.toml` from this repo, but with complete new files)
- [ ] update the version and branch Makefile target
- [ ] requirements.txt should be empty when created new repo from this
- [ ] Put branching strategy on information for developers

**Comment by azataiot** [comment]
- [ ] the badge information should also change when init
- [ ] the make target command can have name init-project

**Comment by azataiot** [comment]
- [ ] the push target should also change based on the tag existence or not

**Comment by azataiot** [comment]
- [ ] A release action should run only when the PR is merged successfully

**Comment by azataiot** [comment]
- [ ] fix the Make branch so that it will list the release types also like in choices
